### ISSUE TITLE
Nothing happens?

### ISSUE THREAD

**Issue by slimcdk** [lociii/homeassistant-csgo#1]
Hi! Cool integration, but it does not work. Atleast not for me.

I've added the integration using HACS.
Copied the uri (it uses a local IP?)
Created the file with the uri.

Log in HA says the .translations directory is deprecated. So I suppose it is loaded corret?
Console in CSGO says that it loaded a Game State Integration: Homeassistant

When I launch a game, notthing shows up in HA.

**Comment by lociii** [comment]
Hey @slimcdk,

can you please check if the webhook is properly registered?
It should show the "csgo_gamestate" domain in it's name and can be found on "Configuration -> Home Assistant Cloud" section "Webhooks" on the bottom of the page.

If it's there, click "Manage" and copy the URL, open the URL in your browser. does it show "405: Method Not Allowed"?

Can you post the content of your gamestate_integration_homeassistant.cfg and where exactly you placed that file?

Best, Jens

**Comment by slimcdk** [comment]
Sure!

I don't use HA Cloud, but my own dns and domain. So nothing is displayed in Configuration -> Home Assistant Cloud other than the login/sign up screen.

A GET request to the webhook uri shows ``` 405: Method Not Allowed ``` for both my internal IP and public address, that I use.

I'm currently on HA (Core) 0.110, but the problem was the same on version 0.109.6.

My Steam client and CSGO is on Ubuntu 20.04, if that is relevant. Here is my config with the internal IP and the uri that the integration yielded.
```
$ cat cat steam/steamapps/common/Counter-Strike\ Global\ Offensive/csgo/cfg/gamestate_integration_homeassistant.cfg
"HomeAssistant Integration v.1"
{
 "uri" "http://192.168.1.11:8123/api/webhook/69c77a8b455dd667bd49991543171af563dd7afb7d6cfcfe1fe789ce7e39832a"
 "timeout" "5.0"
 "buffer" "0.1"
 "throttle" "0.5"
 "heartbeat" "15.0"
 "data"
 {
   "round" "1" // round phase, bomb state and round winner
 }
}
```

**Comment by lociii** [comment]
Could you try faking a webhook using e.g. Firefox with Rested?
https://addons.mozilla.org/en-US/firefox/addon/rested/

Post the following payload and it should trigger the csgo_bomb_defused event:
`{"round": {"bomb": "defused"}}`

Tested on my instance and works fine.

**Comment by slimcdk** [comment]
Wait, am I expecting the wrong thing to happen?

There should be sensors containig the events, right? Or am I wrong?

I'm using postman for REST testing.
Any GET request to the webhook returns ```405: Method Not Allowed```.

If I do a POST request with the payload as plain text or JSON, I get an ```200: OK```

But I can not find anything in HA. I Tried listning for the event ```csgo_bomb_defused```, but thing happens.

**Comment by lociii** [comment]
You're guessing right. There is no sensor or similar. The only thing this extension does is sending out events.
Check the community thread where I posted my config. https://community.home-assistant.io/t/counter-strike-global-offensive-game-state-integration/175505

**Comment by slimcdk** [comment]
Ah, alright! I'll take a look at it.

So this is the event fired from HA itself. Works fine.
![image](https://user-images.githubusercontent.com/23029789/81929121-b5014f00-95e6-11ea-97b5-7222940e1ec9.png)


This is from postman. Nothing happens
![image](https://user-images.githubusercontent.com/23029789/81929276-0f021480-95e7-11ea-93d3-7a967fa83b95.png)

**Comment by slimcdk** [comment]
How could I debug this further?

**Comment by lociii** [comment]
Try webhook component level debugging to see if and how the event arrives.

```yaml
logger:
  default: critical
  logs:
    # log level for webhook integration
    homeassistant.components.webhook: debug
```

**Comment by slimcdk** [comment]
Still no success. This is the full log regarding csgo and webhook entries.
Looks like it is receiving the request. I'll try to debug your code tomorrow or this weekend.

This is my Home Assistant configuration. https://github.com/slimcdk/sn-worker-02/tree/master/services/homeassistant

```
homeassistant    | 2020-05-14 20:00:21 INFO (SyncWorker_2) [homeassistant.loader] Loaded csgo_gamestate from custom_components.csgo_gamestate
homeassistant    | 2020-05-14 20:00:56 INFO (SyncWorker_17) [homeassistant.loader] Loaded webhook from homeassistant.components.webhook
homeassistant    | 2020-05-14 20:03:22 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for csgo_gamestate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
homeassistant    | 2020-05-14 20:05:57 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for d05375a2f8820dec24c4850f6752f425773eaa97e0b80d3a77ec1c0013b63679
homeassistant    | 2020-05-14 20:05:59 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for f2f460184c9c7126799210fe274481da10823dd7fb161eabc0ca46b5ea459a37
homeassistant    | 2020-05-14 20:06:06 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for 69c77a8b455dd667bd49991543171af563dd7afb7d6cfcfe1fe789ce7e39832a
homeassistant    | 2020-05-14 20:06:07 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for 69c77a8b455dd667bd49991543171af563dd7afb7d6cfcfe1fe789ce7e39832a
homeassistant    | 2020-05-14 20:06:20 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for 69c77a8b455dd667bd49991543171af563dd7afb7d6cfcfe1fe789ce7e39832a
homeassistant    | 2020-05-14 20:06:22 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for 69c77a8b455dd667bd49991543171af563dd7afb7d6cfcfe1fe789ce7e39832a
homeassistant    | 2020-05-14 20:06:22 DEBUG (MainThread) [homeassistant.components.webhook] Handling webhook POST payload for 69c77a8b455dd667bd49991543171af563dd7afb7d6cfcfe1fe789ce7e39832a
```

**Comment by slimcdk** [comment]
Hi again.

Didn't get to do much debugging, because all of a sudden, it started working!
Don't know what fixed it. I updated to 0.110 and changed a bunch of others things aswell. I did notice that there was a significant delay, so perhaps it have worked all the time, but me being eager.

However, the 'freeze' event seems to be fired, when a round is over and not when there is a freeze time?

**Comment by lociii** [comment]
> Hi again.
> 
> Didn't get to do much debugging, because all of a sudden, it started working!
> Don't know what fixed it. I updated to 0.110 and changed a bunch of others things aswell. I did notice that there was a significant delay, so perhaps it have worked all the time, but me being eager.
How much delay are you talking about? On my setup, it's max. 0.5 to 1 second.
How are you running HomeAssistant? Is there also a delay on receiving the webhook (see logs)?

> However, the 'freeze' event seems to be fired, when a round is over and not when there is a freeze time?
Well. The integration only does what CSGO reports. See https://github.com/lociii/homeassistant-csgo/blob/master/custom_components/csgo_gamestate/gamestate.py#L53
If it calls for a freezetime, then it's freezetime. Round end should fire "csgo_round_ended" events.

**Comment by IBeRamen** [comment]
@slimcdk Where were you able to find the webhook ID (In your case: 69c77a8b455dd667bd49991543171af563dd7afb7d6cfcfe1fe789ce7e39832a) in Home Assistant? I enabled Webhooks Logging and fired some events in Home Assistant events tab and I don't see any payload posts in the logs.

**Comment by lociii** [comment]
> @slimcdk Where were you able to find the webhook ID (In your case: 69c77a8b455dd667bd49991543171af563dd7afb7d6cfcfe1fe789ce7e39832a) in Home Assistant? I enabled Webhooks Logging and fired some events in Home Assistant events tab and I don't see any payload posts in the logs.

The events you might fire from the dev tools are not webhooks.
This integration works like:
1. CSGO sends a JSON POST payload to the HomeAssistant webhook address
2. HomeAssistant parses and interprets this data and eventually fires one of the csgo_* events
3. One of your automations should listen to that event and trigger some action

**Comment by IBeRamen** [comment]
> > @slimcdk Where were you able to find the webhook ID (In your case: 69c77a8b455dd667bd49991543171af563dd7afb7d6cfcfe1fe789ce7e39832a) in Home Assistant? I enabled Webhooks Logging and fired some events in Home Assistant events tab and I don't see any payload posts in the logs.
> 
> The events you might fire from the dev tools are not webhooks.
> This integration works like:
> 
> 1. CSGO sends a JSON POST payload to the HomeAssistant webhook address
> 2. HomeAssistant parses and interprets this data and eventually fires one of the csgo_* events
> 3. One of your automations should listen to that event and trigger some action

Gotcha, that makes sense. However what should do I put for "URI:" in the Game State Integration config (that goes in the cfg folder for CSGO) if I am not using HomeAssistant Cloud?

**Comment by lociii** [comment]
I've never tested the integration without the cloud service but the last step of the integration setup should show the webhook url. 
@IBeRamen if you have further questions, please open another issue as your questions aren't related to @slimcdk's

**Comment by IBeRamen** [comment]
> I've never tested the integration without the cloud service but the last step of the integration setup should show the webhook url.
> @IBeRamen if you have further questions, please open another issue as your questions aren't related to @slimcdk's

No problem, sorry about that. Opened up #2

**Comment by lociii** [comment]
I'll close this one now as #2 has been resolved and the OP has no issues anymore.
