### ISSUE TITLE
Did my team win?

### ISSUE THREAD

**Issue by a-waider** [lociii/homeassistant-csgo#13]
Hey, 

really like your integration :) Is there a way to determine, if my team won? I listened to the output from the steam game states and found the following:

```
{
        "round": {
                "phase": "over",
                "win_team": "CT"
        },
        "player": {
                "state": {
                        "health": 100,
                        "armor": 100,
                        "helmet": true,
                        "defusekit": true,
                        "flashed": 0,
                        "smoked": 0,
                        "burning": 0,
                        "money": 6650,
                        "round_kills": 3,
                        "round_killhs": 1,
                        "equip_value": 4500
                }
        },
        "previously": {
                "round": {
                        "phase": "live"
                },
                "player": {
                        "state": {
                                "money": 3800,
                                "round_kills": 2,
                                "round_killhs": 0
                        }
                }
        },
        "added": {
                "round": {
                        "win_team": true
                }
        }
}
```

There is a field ["added"]["round"]["win_team"]. Do you know what exactly this means? Or to be more concisely: is this the information I'm looking for?

**Comment by lociii** [comment]
The attribute to pay attention to is `round / win_team`.
Thankfully @Leomm04 already implemented this already in #5 
The addon will fire `csgo_round_win_ct` and `csgo_round_win_t` signals depending on which team won the round. However I did not see any way to find out which team your player belongs to.

**Comment by a-waider** [comment]
Yeah, I saw these fields. But thanks for your answer.

Closing because it seems not possible.

**Comment by jvgoch** [comment]
In the Player_ID component the team the player is in is passed trough:
```{
    "player": {
            "steamid": "76561197984957084",
            "clan": "Clan Tag",
            "name": "Player Name",
            "observer_slot": 1,
            "team": "T", <--------------------------------------
            "activity": "playing"
    },
    "previously": {
            "player": {
                    "steamid": "76561197984957085",
                    "name": "Other Player Name",
                    "observer_slot": 0
            }
    },
    "added": {
            "player": {
                    "clan": true
            }
    }
}```
You could compare this with the win_team value and determine which team won that way.

**Comment by lociii** [comment]
That's right. How would you expect this to be sent as an event?

**Comment by jvgoch** [comment]
erm csgo_round_win_player seems logical to me.

**Comment by lociii** [comment]
SGTM. Feel free to open a pull request for it.

**Comment by lociii** [comment]
FYI: This integration will be deprecated as I released a new system for integrating Home Assistant in Overwolf.
The new one supports lots of games with less hustle to set up.

It's available through HACS and the Overwolf store.
See https://github.com/lociii/homeassistant-overwolf-status and https://github.com/lociii/overwolf-homeassistant-webhook for details.
