### ISSUE TITLE
Setup works but nothing happen

### ISSUE THREAD

**Issue by fknezevic** [lociii/homeassistant-csgo#18]
I'm not really familiar with all of this. But I installed the repofrom HACS then I added it in integrations. I have now a webhook in the list.
I copied the webhook link into the cfg I created in the csgo folder but nothing happens.

I tried replacing my duckdns url by the IP so I have :
`https://192.168.1.52:8123/api/webhook/47652722ff17e245b246bb1b20cea1cea5168dc02153f4cf12e65937733d0047`

I tried a game, nothing is triggered, my webhook don't have any kind of sensor or something.

**Comment by lociii** [comment]
Did you set up any automation that reacts on the event triggered by this integration?
See https://community.home-assistant.io/t/counter-strike-global-offensive-game-state-integration/175505 for an example.

**Comment by lociii** [comment]
No feedback
