### ISSUE TITLE
Setting up without HomeAssistant Cloud

### ISSUE THREAD

**Issue by IBeRamen** [lociii/homeassistant-csgo#2]
I followed the instructions and tested that it's configured correctly and communicating with my lights using the developer tools and the call feature in Home Assistant. However for the CSGO config to create the webhook URL I am unable to get it connect locally without using HomeAssistant cloud.

When I setup the plugin using HACS I installed the master branch (Since the master branch fixed the .translation issue of it being moved). However I never got a prompt showing me what my webhook URL is.

Is there a way to get the webhook URL?

My config:

```
"HomeAssistant Integration v.1"
{
 "uri" "http://192.168.1.35:8123/api/webhook/"
 "timeout" "5.0"
 "buffer" "0.1"
 "throttle" "0.5"
 "heartbeat" "15.0"
 "data"
 {
   "round" "1" // round phase, bomb state and round winner
 }
}
```

I need to know what ID to put after /webhook/ as shown in #1

**Comment by lociii** [comment]
Is "http://192.168.1.35:8123/api/webhook/" everything that's shown on the final setup step?

First step:
![csgo_install_step1](https://user-images.githubusercontent.com/366967/83047820-34603b00-a049-11ea-83a2-163f6714e797.png)

Second (final) step:
![csgo_install_step2](https://user-images.githubusercontent.com/366967/83047837-3c1fdf80-a049-11ea-9f65-726557d04214.png)

As you can see, it shows a full webhook URL to me.

**Comment by IBeRamen** [comment]
Selecting CS:GO HomeAssistant from HACS and installing it, I do not get those prompts, it installs after ~3 mins or so then I refresh the page and it just says it's installed no prompt with the webhook appears.

**Comment by lociii** [comment]
Alright. Then you just downloaded the integration but didn't set it up yet at all.
HACS is basically just a downloading and updating tool.

To set it up, go to "Configuration -> Integrations" and hit the + button.
I'll clarify the procedure in the README.

**Comment by lociii** [comment]
Updated the README.
However the HACS instructions already contained that information. Sometimes, reading is king! :P

**Comment by IBeRamen** [comment]
I usually never open up issues for help setting something up, I probably read those instructions 3 times and missed it every time, that's what I get for doing this at 2am. Thank you for your help!

**Comment by lociii** [comment]
No problem. Let me know if it works out.
Would also love to see a video of your use case.

**Comment by NgLoader** [comment]
How to setup uri with the local uri

### Please note!
First of all you need to generate the uri with the normal way.

### Find your webhook id
You can find the webhook_id in ``config/.storage/core.config_entries`` and search for ``csgo_gamestate``
You find something like that:
```json
{
        "entry_id": "***",
        "version": 1,
        "domain": "csgo_gamestate",
        "title": "Webhook",
        "data": {
          "webhook_id": "***", <-- Copy the webhook id
          "cloudhook": true
        },
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": null,
        "disabled_by": null
      }
```

Now you can replace your url like that one and replace WEBHOOK_ID with your webhook id:
"uri" "http://homeassistant.local/api/webhook/WEBHOOK_ID"

**Comment by lociii** [comment]
Thanks for the summary, @NgLoader 
Please feel free to open a pull request to update the README.

Side note: I'm currently working on an [Overwolf integration](https://github.com/lociii/homeassistant-overwolf-status) that will support many more games and will replace this integration. However the Overwolf one will only work with nabu.casa Webhook URLs.
