### ISSUE TITLE
URI not shown after install

### ISSUE THREAD

**Issue by antoniassiph** [lociii/homeassistant-csgo#3]
After install via HACS no URI is provided. The popup closes without any confirmation.
Server logs and client side devtools are useless (no errors or meaningful data).

Any known issue or fix ideia?

Similar: #2

**Comment by lociii** [comment]
#2 was never an issue of this integration but a lack of understanding what HACS is and what you need to **set up** an integration that is **installed** by HACS.
After installing the integration with HACS, did you follow the [HACS instructions](https://github.com/lociii/homeassistant-csgo/blob/master/info.md) on how to set it up?

Please give detailed information what steps you took and in which order. Screenshots of each step appreciated.

**Comment by antoniassiph** [comment]
I've installed it as usual, like any other HACS integration

![HACS-Home-Assistant-Opera-2020-06-29-15-20-38](https://user-images.githubusercontent.com/8649042/86044578-a3ea9100-ba20-11ea-9289-6f0e49a0255f.gif)

**Comment by lociii** [comment]
Again. Please read the instructions linked in the comment above.

**Comment by antoniassiph** [comment]
I finally got it. I read "Go to the integrations page" as "Go to the HACS integrations page", not "Go to the HA integrations page"
