### ISSUE TITLE
enhancement: could you add a game launch event?

### ISSUE THREAD

**Issue by rickoneeleven** [lociii/homeassistant-csgo#9]
would love to stop my torrents when the game is launched.

loving it by the way, thank you ❤❤❤❤

**Comment by rickoneeleven** [comment]
just to add to this, the reason I can't use round start is, my latency is too high to match for competitive until i've stopped torrents, so the rounds won't start. i already have all my torrent stuff hooked into HA. Thanks

**Comment by lociii** [comment]
Unfortunately there is no real event sent when the game starts. We could somehow work around by firing the signal when we receive the first event and store the game active state until the game is closed.
However if the game closed event isn't received/processed properly, the integration will assume that the game is still running.

**Comment by rickoneeleven** [comment]
thanks for coming to me @lociii, for the most part I've bound the "torrent stop" automation to "round start", it's a little late in the process but it is all working. uses this automation daily, thanks for all your commits my friend.

think it's even encouraged my daughter to want to play, she loves seeing all the live light interactions ❤❤❤

**Comment by lociii** [comment]
Thanks for the feedback.
Will close this issue now as I don't see a proper solution.
